name: MsClansAddons
description: A plugin that adds lots og coll stuff to the clans plugin
version: '${project.version}'
main: org.matic.msclansaddons.MsClansAddons
api-version: '1.16'
depend: [Clans]
commands:
  spawn:
    description: Teleport to spawn
    usage: /spawn
  wild:
    description: Randomly Teleports You
    usage: /wild