name: MsClansAddons
description: A plugin that adds lots og coll stuff to the clans plugin
version: '${project.version}'
main: org.matic.msclansaddons.MsClansAddons
api-version: '1.16'
depend: [Clans]